version: 2.0
orbs:
  aws-cli: circleci/aws-cli@0.1
  orb-tools: circleci/orb-tools@9.0
  aws-code-deploy: circleci/aws-code-deploy@1.0.1

jobs:
  build:
    working_directory: ~/
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - run: mvn -Dmaven.test.skip=true package
      - persist_to_workspace:
         root: ./
         paths:
           - target/
      - aws-code-deploy/push-bundle:
          application-name: sampleapp
          bundle-source: ~/ruby-stage
          bundle-bucket: sampleappraj
          bundle-key: sample/$CIRCLE_PROJECT_REPONAME-${CIRCLE_BRANCH}-$CIRCLE_TAG-<< pipeline.git.revision	>>-<< pipeline.git.tag	>>  
  deploy:
   
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - attach_workspace:
          at: .
      - run: 
          name: python3 setup
          command: sudo apt-get update && sudo apt-get install python3-pip -y
      - aws-cli/setup
      - aws-code-deploy/deploy-bundle:
          application-name: sampleapp
          deployment-group: sampleapp-group
          bundle-bucket: sampleappraj
          bundle-key: sample/$CIRCLE_PROJECT_REPONAME-${CIRCLE_BRANCH}-$CIRCLE_TAG-<< pipeline.git.revision	>>-<< pipeline.git.tag	>>           

  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - attach_workspace:
          at: ./target
      - run: mvn test
workflows:
   version: 2
   build-deploy: 
    jobs:
      - build
      - deploy:
          requires:
            - build
