---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: tomcat-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tomcat-demo
    spec:
      containers:
      - name: tomcat-demo
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 558811456770.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo:1d52e085c4cc5d5e5031cfaf0cb2c8d43b48fd02
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
