---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
      matchLabels:
        app.kubernetes.io/name: tomcat-demo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: tomcat-demo
    spec:
      containers:
      - name: aws-example-octodex
        # image: 00000000000000.dkr.ecr.my-region.amazonaws.com/example-eks:tag
        image: 558811456770.dkr.ecr.ap-south-1.amazonaws.com/my-ecr-repo:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
