apiVersion: v1
kind: Service
metadata:
  name: tomcat-demo
  labels:
    app: tomcat-demo 
spec:
#   type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
      app: tomcat-demo
